#!/usr/bin/env bash

## BOOTSTRAP ##
source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/lib/oo-framework.sh"

import lib/type-core
import lib/system/00_log
import lib/lars/logger
import lib/lars/check
import lib/lars/test_con

OTC_MANAGER_SRC=http://downloads.sourceforge.net/project/openthinclient/installer/openthinclient-2.1-Pales.jar?r=http%3A%2F%2Fsourceforge.net%2    Fprojects%2Fopenthinclient%2F&ts=1450438652&use_mirror=netcologne
OTC_INSTALL_SRC=
wget -q OTC_MANAGER_SRC -o otc-manager.jar
check -f $? "fetching manager" "wget"

